fragment LensProfileFieldsFragment on lens_profiles {
  lensHandle
  isUserFollowing
  isFollowPending
  createdAt
}

fragment FarcasterProfileFragment on farcaster_profiles {
  name
  isUserFollowing
  createdAt
}

fragment ProfileFieldsFragment on profiles {
  id
  username
  isUserFollowing
  createdAt
  credLevel
  badge
  phaverFrens
  verification
  verified
  lensProfile {
    ...LensProfileFieldsFragment
  }
  farcasterProfile {
    ...FarcasterProfileFragment
  }
  profileAggregates {
    followerCount
    followingCount
  }
}

fragment FollowerFieldsFragment on followers {
  followedProfile {
    ...ProfileFieldsFragment
  }
  createdAt
}

fragment QuotaFollowsFragment on QuotaFollows {
  quotaType
  available
  maximum
  monthlyAvailable
  monthlyMaximum
}

fragment QuotaLensApiFragment on QuotaLensApi {
  quotaType
  dailyAvailable
  dailyMaximum
  hourlyAvailable
  hourlyMaximum
}

fragment QuotaLensPublicationFragment on QuotaPublications {
  available
  maximum
  quotaType
}